---
kind: pipeline
type: docker
name: oracle_oci

steps:

- name: Apply Ansible playbook
  image: alesson23/terraforandansible:1.0.0
  environment:
    PRIVATE_KEY:
      from_secret: private_key
    ANSIBLE_VAULT_VALUE:
      from_secret: ansible_vault_value
  commands:
  - mkdir -p ~/.ssh/
  - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - unset private_key
  - ansible-playbook --vault-id "$ANSIBLE_VAULT_VALUE" -i Oracle/hosts/oracle -u opc --ssh-common-args='-o StrictHostKeyChecking=no' Oracle/main.yml
  when:
    branch:
      - main
