# This is a basic workflow to help you get started with Actions
name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: alesson23/terraforandansible:1.0.0
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: ""
  deployAnsible:
    needs: build
    runs-on: alesson23/terraforandansible:1.0.0
    steps:
    - uses: actions/checkout@v1
    - uses: ./ansible_oci/Oracle/main.yml
      with: 
        playbook: main.yml
        inventory: hosts/oracle
        vault-id: .ansible.vault 
